GaganSingh/urls.py
from django.urls import path
from GaganSingh import views

urlpatterns=[
  path('',views.home,name='home'),
  path('timeline',views.timeline,name='timeline'),
  path('Projects/<int:projectid>',views.project,name='project'),
  path('Projects/',views.viewpeoject,name='finalproject'),
  path('Profile',views.profile,name='profile'),
  path('stack',views.stack,name='stack'),
  ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from portfolio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GaganSingh.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

GaganSingh/models.py
from django.db import models

class ProfileGagan(models.Model):
	Name=models.CharField(max_length=100,default='Gagan Singh')
	Image=models.ImageField(upload_to='profilepic')
	Bio=models.CharField(max_length=10000,null=True)
	currently=models.CharField(max_length=100,blank=True)


class EducationGagan(models.Model):
	profilegagan=models.ForeignKey(ProfileGagan,on_delete=models.CASCADE)
	institute=models.CharField(max_length=500,blank=True)
	joiningperiod=models.CharField(max_length=150,blank=True)
	course=models.CharField(max_length=500,blank=True)
	date=models.DateTimeField(blank=True)
	score=models.CharField(max_length=10,blank=True)

	

class ProjectsGagan(models.Model):
	profilegagan=models.ForeignKey(ProfileGagan,on_delete=models.CASCADE)
	Name=models.CharField(max_length=100,blank=True)
	desc=models.CharField(max_length=1000,blank=True)
	Glink=models.CharField(max_length=200,blank=True,null=True)
	Llink=models.CharField(max_length=200,blank=True,null=True)

	def __str__(self):
		return self.Name

class ProjectPara(models.Model):
	projectsgagan=models.ForeignKey(ProjectsGagan,on_delete=models.CASCADE)
	paragraph=models.CharField(max_length=10000,blank=True)

class ProjectImage(models.Model):
	projectsgagan=models.ForeignKey(ProjectsGagan,on_delete=models.CASCADE)
	image=models.ImageField(upload_to='projectimage')

class Timeline(models.Model):
	profilegagan=models.ForeignKey(ProfileGagan,on_delete=models.CASCADE)
	dateof=models.DateTimeField(blank=True)
	heading=models.CharField(max_length=200,blank=True)
	bio=models.CharField(max_length=500,blank=True)


class TechnicalStack(models.Model):
	profilegagan=models.ForeignKey(ProfileGagan,on_delete=models.CASCADE)
	name=models.CharField(max_length=200,blank=True)
	image=models.ImageField(upload_to='technical_stack')
	desc=models.CharField(max_length=1000,blank=True)

	def __str__(self):
		return self.name

class Hobbies(models.Model):
	profilegagan=models.ForeignKey(ProfileGagan,on_delete=models.CASCADE)
	name=models.CharField(max_length=100,blank=True)


# Create your models here.

GaganSingh/views.py
from django.shortcuts import render,get_object_or_404
from .models import ProfileGagan,EducationGagan,ProjectsGagan,ProjectPara,ProjectImage,Timeline,TechnicalStack,Hobbies

def home(request):
   query=ProfileGagan.objects.all()
   projectcount=0
   pstack=0
   for k in query:
   	   projectcount=k.projectsgagan_set.all().count()
   	   pstack=k.technicalstack_set.all().count()
   return render(request,'Intro.html',{'query':query,'projectcount':projectcount,'pstack':pstack})

def timeline(request):
  query=ProfileGagan.objects.all()
  return render(request,'timeline.html',{'query':query})

def project(request,projectid):
  query=get_object_or_404(ProjectsGagan,id=projectid)
  return render(request,'projects.html',{'query':query})

def profile(request):
  query=ProfileGagan.objects.all()
  projectcount=0
  pstack=0
  for k in query:
    projectcount=k.projectsgagan_set.all().count()
    pstack=k.technicalstack_set.all().count()
  return render(request,'profile.html',{"query":query,'projectcount':projectcount,'pstack':pstack})


def stack(request):
  query=ProfileGagan.objects.all()
  return render(request,'stack.html',{'query':query})

def viewpeoject(request):
  query=ProfileGagan.objects.all()
  return render(request,'post.html',{'query':query})
# Create your views here.

GaganSingh/templates/Intro.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
<div class="MainBody">
	{% for p in query %}
	<div class="Profile">
		<div class="ProfileHeading">Profile at a glance</div>
		<div class="ProfileBody">
			<div class="ProfileImageContainer"><img src="{{ p.Image.url }}"/></div>
			<div class="ProfileAbout">
				<div class="ProfileAboutRow">
				    <div class="ProfileFirst">Name</div>
				    <div class="ProfileFirst" style="color:#e0474c;">{{ p.Name }}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Bio</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ p.Bio }}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Currently</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ p.currently }}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Projects</div>
            
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ projectcount }}</div>
                
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Stack</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ pstack}}</div>
			    </div>
                <div class="ProfileAboutRow" style="text-align: center;">
                   <div style="margin:auto;color:#e0474c;"> <a href="{%url 'profile' %}" style="color: #e0474c;font-weight: bolder;">View Profile</a></div>
                </div>
			</div>
		</div>
    </div>{% endfor %}
  
 <!-- {% if forloop.counter|mod:3 %}{% endif %} -->
    <div class="Projects">
    	<div class="ProfileHeading">Projects</div>
        {% for q in query %}
            {% for pro in q.projectsgagan_set.all %}
            {% if forloop.counter|mod:3 == 1 %}
            <div class="ProjectRow">
            {% endif %}
    		<div class="ProjectSampleCard">
                {% for im in pro.projectimage_set.all|slice:":1" %}
    			<img src="{{ im.image.url }}"/>
                {% endfor %}
    			<h3>{{ pro.Name }}</h3>
    			<p>{{ pro.desc }}</p>
    			<a href="Projects/{{pro.id}}" style=""><div>Know More</div></a>
    		</div>
            {% if forloop.counter|mod:3 == 0 %}
             </div>
             {% endif %}
            {% endfor %}
    	
        {% endfor %}
    </div>
   
    <div class="Projects">
    	<div class="ProfileHeading">Technical Stack</div>
        {% for q in query %}
          {% for pro in q.technicalstack_set.all %}
          {% if forloop.counter|mod:3 == 1 %}
    	<div class=ProjectRow>
            {% endif %}
    		<div class="ProjectSampleCard">

    			<img src="{{ pro.image.url  }}"/>
    			<h3>{{ pro.name }}</h3>
    			<p>{{ pro.desc }}</p>
    		</div>
            {% if forloop.counter|mod:3 == 0%}
    	</div>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>

<div class="footer">This website is dynamic unlike other one pages online resume which contains static webpages<br/>Website coded and maintained by Gagan Singh<br/>All rights reserved<br/>Sapora Inc.</div>



</div>
<style type="text/css">
	.MainBody{
		position: absolute;
		top: 50px;
		left: 0px;
		width: 100%;
		height: auto;
        padding-bottom: 50px;
	}
	.Profile{
		width: 100%;
		height: auto;
		background-color: transparent;
		box-shadow: 4px 2px 2px 2px rgba(0,0,0,0.625);
	}
	.ProfileHeading{
		padding-top: 5px;
        width: 100%;
        background-color: #fff;
        text-align: center;
        height: 25px;
        background-color: #000;
		color: #e0474c;
		font-weight: bolder;
	}
	.ProfileBody{
		width: 100%;
		background-color: transparent;
		height: auto;
	}
	.ProfileImageContainer{
		margin:auto;
		margin-top: 10px;
		width: 150px;
		height: 150px;
		border-radius: 75px;
		background-color: #f7f7f7;
	}
	.ProfileImageContainer img{
		width: 100%;
		height: 100%;
		border-radius: 50%;
		object-fit: cover;
	}
	.ProfileAbout{
		margin-top: 20px;
	    width: 100%;
	    height: auto;
	    background-color: transparent;
    }
    .ProfileAboutRow{
    	display: flex;
    	justify-content: space-between;
    	width: 100%;
    	height: 50px;
    }
    .ProfileFirst{
    	display: inline-block;
    	width: 50%;
    	height: 100%;
    	text-align: center;
    }
    .Projects{
    	width: 100%;
    	height: auto;
    	background-color: #f7f7f7;
    	padding-bottom: 20px;
    }
    .ProjectRow{
    	margin-top: 20px;
    	width: 92%;
    	height: auto;
    	background-color: transparent;
    	display: flex;
    	justify-content: space-between;
    	padding-left: 4%;
    	padding-right: 4%;
    	padding-bottom: 20px;
    }
    .ProjectSampleCard{
    	width: 250px;
    	height: auto;
    	background-color: #ffffff;
    	border-radius: 10px;
    	border: 1.5px solid rgba(0,0,0,0.125);
    	box-shadow: 8px 8px 8px 6px rgba(0,0,0,0.125);
    }
    .ProjectSampleCard img{
    	border-top-left-radius: 10px;
    	border-top-right-radius: 10px;
    	width: 100%;
    	height: 100px;
    	object-fit: cover;
    }
    .ProjectSampleCard h3{
    	width: 100%;
    	margin-top: -5px;
    	text-align: center;
    }
    .ProjectSampleCard p{
    	padding-left: 5%;
    	margin-top: -17px;
    	width: 90%;
    	height: 100px;
    	background-color:transparent;
}
    .ProjectSampleCard div{
    	margin: auto;
    	width: 100px;
    	height: 20px;
    	padding-top: 5px;
    	background-color:#e0474c;
    	color: #fff;
    	margin-top: 0px;
    	text-align: center;
    	border-radius: 10px;
    }
     .footer{
     	background-color: #f7f7f7;
        width: 100%;
        height: auto;
        color: #e0474c;
        text-align: center;
        font-weight: bolder;
  }
    @media(max-width: 450px){
    	.ProjectRow{
    		display: block;
    		margin-bottom: -35px;
    	}
    	.ProjectSampleCard{
    		width: 80%;
    		height: 300px;
    		margin-left: 10%;
    		margin-bottom: 15px;
    	}   	
    }
</style>
{% endblock %} 

GaganSingh/templates/post.html
{% extends 'base.html' %}
{% block content %}
{% load mathfilters %}
<div class="MainBody">

     <div class="Projects">
        <div class="ProfileHeading">Projects</div>
        {% for q in query %}
            {% for pro in q.projectsgagan_set.all %}
            {% if forloop.counter|mod:2 == 1 %}
            <div class="ProjectRow">
            {% endif %}
            <div class="ProjectSampleCard">
                {% for im in pro.projectimage_set.all|slice:":1" %}
                <img src="{{ im.image.url }}"/>
                {% endfor %}
                <h3>{{ pro.Name }}</h3>
                <p>{{ pro.desc }}</p>
                <a href="/Projects/{{pro.id}}" style=""><div>Know More</div></a>
            </div>
            {% if forloop.counter|mod:2 == 0 %}
             </div>
             {% endif %}
            {% endfor %}
        
        {% endfor %}
    </div>

	
    </div>
    

	<div class="footer">This website is dynamic unlike other one pages online resume which contains static webpages<br/>Website coded and maintained by Gagan Singh<br/>All rights reserved<br/>Sapora Inc.</div>
</div>
<style type="text/css">
	.MainBody{
        position: absolute;
        top: 50px;
        left: 0px;
        width: 100%;
        height: auto;
        padding-bottom: 50px;
    }
	.ProfileHeading{
		padding-top: 5px;
        width: 98%;
        text-align: left;
        height: 50px;
        background-color: #f7f7f7;
		color: #e0474c;
		font-weight: bolder;
        padding-left: 2%;
		font-size: 30px;
	}
	.Projects{
    	width: 100%;
    	height: auto;
    	background-color: #f7f7f7;
    	padding-bottom: 20px;
    }
    .ProjectRow{
    	margin-top: 20px;
    	width: 92%;
    	height: auto;
    	background-color: transparent;
    	display: flex;
    	justify-content: space-between;
    	padding-left: 4%;
    	padding-right: 4%;
    	padding-bottom: 20px;
    }
    .ProjectSampleCard{
    	width: 45%;
    	height: auto;
    	background-color: #ffffff;
    	border-radius: 10px;
    	border: 1.5px solid rgba(0,0,0,0.125);
    	box-shadow: 8px 8px 8px 6px rgba(0,0,0,0.125);
    }
    .ProjectSampleCard img{
    	border-top-left-radius: 10px;
    	border-top-right-radius: 10px;
    	width: 100%;
    	height: 300px;
    	object-fit: cover;
    }
    .ProjectSampleCard h3{
    	width: 100%;
    	margin-top: -5px;
    	text-align: center;
    }
    .ProjectSampleCard p{
    	padding-left: 5%;
    	margin-top: -17px;
    	width: 90%;
    	height: auto;
    	background-color:transparent;
}
    @media(max-width: 450px){
    	.ProjectRow{
    		display: block;
    		
    	}
    	.ProjectSampleCard{
    		width: 80%;
    		height: auto;
    		margin-left: 10%;
    		margin-bottom: 15px;
    	}
        .ProjectSampleCard img{
            width: 100%;
            max-height: 180px;
        }   	
    }
	.footer{
     	background-color: #f7f7f7;
        width: 100%;
        height: auto;
        color: #e0474c;
        text-align: center;
        font-weight: bolder;
    }
    .ProjectSampleCard div{
        margin: auto;
        width: 100px;
        height: 20px;
        padding-top: 5px;
        background-color:#e0474c;
        color: #fff;
        margin-top: 0px;
        text-align: center;
        border-radius: 10px;
    }
</style>
{% endblock %}

GaganSingh/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{% load mathfilters %}
<div class="MainBody">


<div class="Profile">
    {% for q in query %}
		<div class="ProfileHeading">Profile at a glance</div>
		<div class="ProfileBody">
			<div class="ProfileImageContainer"><img src="{{ q.Image.url }}"/></div>
			<div class="ProfileAbout">
				<div class="ProfileAboutRow">
				    <div class="ProfileFirst">Name</div>
				    <div class="ProfileFirst" style="color:#e0474c;">{{ q.Name }}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Bio</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ q.Bio}}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Currently</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ q.currently }}</div>
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Projects</div>
			    	{% if projectgagan %}
                    <div class="ProfileFirst" style="color:#e0474c;">{{ projectgagan }}</div>
                    {% else %}
                    <div class="ProfileFirst" style="color:#e0474c;">0</div>
                    {% endif %}
			    </div>
			    <div class="ProfileAboutRow">
			    	<div class="ProfileFirst">Stack</div>
			    	<div class="ProfileFirst" style="color:#e0474c;">{{ pstack }}</div>
			    </div>
			</div>
		</div>
    </div>{% endfor %}



     <div class="Projects">
    	<div class="ProfileHeading">Education</div>
        {% for q in query %}
        {% for pro in q.educationgagan_set.all %}
        {% if forloop.counter|mod:2 == 1 %}
    	<div class=ProjectRow>
            {% endif %}
    		<div class="ProjectSampleCard">
    			<div class="Institute">{{ pro.institute }} </div> 
    			<div class="Institute" style="height: 20px;color: #9adcf9;padding-top: 0px;">{{ pro.joiningperiod }}</div>
    			<div class="Institute">
    				<div class="SubInstitute">Course</div>
    				<div class="SubInstitute" style="color:#e0474c ">{{ pro.course }}</div>
    			</div>
    			<div class="Institute">
    				<div class="SubInstitute">Score</div>
    				<div class="SubInstitute" style="color:#e0474c ">{{ pro.score }}</div>
    			</div>
    		</div>

    		{% if forloop.counter|mod:2 == 0 %}

    	</div>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>

    <div class="Projects">
    	<div class="ProfileHeading">Hobbies</div>
    	<div style="width: 90%;padding-left: 5%;padding-right: 5%;align-content: center;">
            {% for q in query %}
            {% for pro in q.hobbies_set.all %}
    	<div class="ProjectRowBullet">{{ pro.name }}</div>
    	{% endfor %}{% endfor %}
    	</div>
    </div>

<div class="footer">This website is dynamic unlike other one pages online resume which contains static webpages<br/>Website coded and maintained by Gagan Singh<br/>All rights reserved<br/>Sapora Inc.</div>

</div>
<style type="text/css">
     .ProjectRowBullet{
     	margin: auto;
     	margin-bottom: 20px;
     	display: inline-block;
     	padding-top: 5px;
     	border-radius: 20px;
     text-align: center; 
     	height: 25px;
     	width:100px;
     	background-color: #e0474c;
     	color: #ffffff;
     }
     .ProjectRow{
    	margin-top: 20px;
    	width: 92%;
    	height: auto;
    	background-color: transparent;
    	display: flex;
    	justify-content: space-between;
    	padding-left: 4%;
    	padding-right: 4%;
    	padding-bottom: 20px;
    }
    .SubInstitute{
    	display: inline-block;
    	width: 48%;
    	height: 100%;
    	text-align: center;
    }
    body{background-color: #f7f7f7;}
    .MainBody{
		position: absolute;
		top: 50px;
		left: 0px;
		width: 100%;
		height: auto;
        padding-bottom: 60px;
	}
	.Profile{
		width: 100%;
		height: auto;
		background-color: #ffffff;
		}
    .ProfileHeading {
    padding-top: 5px;
    width: 98%;
    text-align: left;
    height: 50px;
    background-color: #f7f7f7;
    color: #e0474c;
    font-weight: bolder;
    padding-left: 2%;
    font-size: 30px;
}
	.ProfileBody{
		position: relative;
		top:-10px;
		width: 100%;
		background-color: transparent;
		height: auto;
		box-shadow: 8px -8px 6px -5px rgba(0,0,0,0.125);
	
	}
	.ProfileImageContainer{
		margin:auto;
		margin-top: 10px;
		width: 150px;
		height: 150px;
		border-radius: 75px;
		background-color: #f7f7f7;
	}
	.ProfileImageContainer img{
		width: 100%;
		height: 100%;
		border-radius: 50%;
		object-fit: cover;
	}
	.ProfileAbout{
		margin-top: 20px;
	    width: 100%;
	    height: auto;
	    background-color: transparent;
    }
    .ProfileAboutRow{
    	display: flex;
    	justify-content: space-between;
    	width: 100%;
    	height: 50px;
    }
    .ProfileFirst{
    	display: inline-block;
    	width: 50%;
    	height: 100%;
    	text-align: center;
    }
     .Projects{
    	width: 100%;
    	height: auto;
    	background-color: #f7f7f7;
    	padding-bottom: 20px;
    }
    .ProjectSampleCard{
    	display: inline-block;
    	width: 45%;
    	height: auto;
    	background-color: #ffffff;
    	border-radius: 10px;
    	border: 1.5px solid rgba(0,0,0,0.125);
    	box-shadow: 8px 8px 8px 6px rgba(0,0,0,0.125);
    }
    .ProjectSampleCard img{
    	border-top-left-radius: 10px;
    	border-top-right-radius: 10px;
    	width: 100%;
    	height: 300px;
    	object-fit: cover;
    }
    .ProjectSampleCard h3{
    	width: 100%;
    	margin-top: -5px;
    	text-align: center;
    }
    .ProjectSampleCard p{
    	padding-left: 5%;
    	margin-top: -17px;
    	width: 90%;
    	height: 350px;
    	background-color:#f7f7f7;
}
.Institute{
	padding-top: 10px;
	width: 100%;
	height: 50px;
	text-align: center;
	font-weight: bolder;
}
    @media(max-width: 450px){
    	.ProjectRow{
    		display: block;
    		margin-bottom: -35px;
    	}
    	.ProjectSampleCard{
    		width: 95%;
    		height: auto;
    		margin-left: 2.5%;
    		margin-bottom: 15px;
    	}   	
    }
	.footer{
     	background-color: #f7f7f7;
        width: 100%;
        height: auto;
        color: #e0474c;
        text-align: center;
        font-weight: bolder;
    }
</style>
{% endblock %}

GaganSingh/templates/projects.html
{% extends 'base.html' %}

{% block content %}
{% load mathfilters %}
<div class="MainBody">
	<div class="container">
		{% for img in query.projectimage_set.all %}
		<img class="mySlides" src="{{ img.image.url }}" style="width: 100%;">
		{% endfor %}

		<button class="w3-button w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
		<button class="w3-button w3-display-right" onclick="plusDivs(1)">&#10095;</button>
		
		
	</div>
	<div class="blog">
		<h3>{{ query.Name }}</h3>
		{% for para in query.projectpara_set.all %}
		<div class="Paragraph">{{ para.paragraph }}</div>
		{% endfor %}

		<div class="Linker">
			{% if query.Glink %}
			<a href="{{ query.Glink }}"><div class="github">View Code on Github</div></a>
			{% endif %}
			{% if query.Llink %}
            <a href="{{ query.Llink }}"><div class="ViewProject">Visit Project</div></a>
            {% endif %}
		</div>

	</div>




</div>
<!--<div class="container">
  <img class="mySlides" src="/media/projectimage/1._skyscraper.jpg" style="width:100%">
  <img class="mySlides" src="/media/projectimage/2._knitting_balls.jpg" style="width:100%">
  <img class="mySlides" src="/media/projectimage/Capture.jpg" style="width:100%">
  

  <button class="w3-button  w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
  <button class="w3-button  w3-display-right" onclick="plusDivs(1)">&#10095;</button>
</div>



</div>-->

<style type="text/css">
    .github,.ViewProject{
    	padding-top: 15px;
    	width: 200px;
    	height: 35px;
    	margin:auto;
    	background-color: #e0474c;
    	text-align: center;
    	color: #fff;
    	margin-top: 10px;
    	border-radius: 20px;
    }
    .github:hover{
    	background-color: #000;
    }
    .ViewProject{background-color: #000;}
    .ViewProject:hover{background-color: #e0474}
    .Linker{
    	width: 100%;
    	height: 50px;
    }
    
    .blog h3{
    	width: 100%;
    	height: 50px;
    	text-align: center;
    	font-family:"-apple-system",BlinkMacSystemFont,Roboto,helvetica,Arial,나눔고딕,sans-serif;
    	font-size: 25px;
    }
    .MainBody{
		position: absolute;
		top: 50px;
		left: 0px;
		width: 100%;
		height: auto;
        padding-bottom: 50px;
	}
	.container{
		background-color: #c0c0c0;
		width: 100%;
		height: 300px;
	}
	.container img{
		width: 100%;
		height: 100%;
		object-fit: cover;
		}
	.w3-button{
		position: absolute;
		top:0px;
		height: 300px;
		background-color: #000000;
		color: #ffffff;
		outline: 0px;
		border:0px;
	}
	.w3-button:hover{
		background-color: #ffffff;
		color: #000000;
	}
	.w3-display-right{
		position: absolute;
		right: 0px;
	}
	.blog{
        width: 100%;
    	height: 400px;
    	background-color: #fff;
    	margin-top: 0px;
    }
    .Paragraph{
    	margin-top: 20px;
    	width: 90%;
    	margin-left: 5%;
    	background-color: transparent;
    	height: auto;
        word-break: break-all;

    }
</style>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>

{% endblock %}